### ISSUE TITLE
[Bug]: No channel logo and banner cant reindex channels

### ISSUE THREAD

**Issue by SalsifiPourri** [tubearchivist/tubearchivist#784] opened 2024-08-08 22:06 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology

## Describe the bug
yesterday it all worked fine, then i installed plex plus the https://github.com/tubearchivist/tubearchivist-plex plugin to get metadatas from tubearchivist, all fine but today, when i download videos, it adds the channel where the video comes from but it does not get the channel logo and banner which is annoying because now in plex, i get no icons for these channels.
![Screenshot 2024-08-09 at 00-04-16 TA Channel About CacaboxTV](https://github.com/user-attachments/assets/553b1f03-8b73-4aa1-bdbd-360d14ad1147)
![Screenshot 2024-08-09 at 00-05-38 Plex](https://github.com/user-attachments/assets/43ce20ce-d756-431b-8497-fdc2343df082)

### Relevant log output

```shell
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,166: WARNING/ForkPoolWorker-2] https://www.youtube.com/channel/UC6izVPg2AiK83K-rqS6AgmA: failed to get info from youtube with message ERROR: [youtube:tab] UC6izVPg2AiK83K-rqS6AgmA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check[0m
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,166: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] UC6izVPg2AiK83K-rqS6AgmA: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check[0m
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,163: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries[0m
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,162: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[0m
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,050: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...[0m
2024/08/08 23:51:27	stdout	[1;33m[2024-08-08 23:51:27,050: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,937: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,937: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,815: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,814: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,413: WARNING/ForkPoolWorker-2] UC6izVPg2AiK83K-rqS6AgmA: get metadata from youtube[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,404: WARNING/ForkPoolWorker-2] UC6izVPg2AiK83K-rqS6AgmA: get metadata from es[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,262: WARNING/ForkPoolWorker-2] validating cookie[0m
2024/08/08 23:51:26	stdout	[1;33m[2024-08-08 23:51:26,251: WARNING/ForkPoolWorker-2] [task][check_reindex] reindex {'channel': ['UC6izVPg2AiK83K-rqS6AgmA']}[0m
```

**Comment by bbilly1** [comment] 2024-08-09 18:05
Same error as mentioned here: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled

Also see workarounds there.

**Comment by SalsifiPourri** [comment] 2024-08-09 18:55
> Same error as mentioned here: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled
> 
> Also see workarounds there.

Not sure this is linked since I can still download videos and at a very good speed, I just can’t re index channels

**Comment by bbilly1** [comment] 2024-08-10 13:36
Because this works fine for me without cookie behind VPN:
```
tubearchivist  | [2024-08-10 15:33:40,442: INFO/MainProcess] Task subscribe_to[38834140-c0b6-4450-bad0-e497e73f3932] received
tubearchivist  | [2024-08-10 15:33:40,442: WARNING/ForkPoolWorker-4] subscribe_to create callback
tubearchivist  | [2024-08-10 15:33:40,446: WARNING/ForkPoolWorker-4] UC6izVPg2AiK83K-rqS6AgmA: get metadata from es
tubearchivist  | [2024-08-10 15:33:40,449: WARNING/ForkPoolWorker-4] {"_index":"ta_channel","_id":"UC6izVPg2AiK83K-rqS6AgmA","found":false}
tubearchivist  | [2024-08-10 15:33:40,450: WARNING/ForkPoolWorker-4] UC6izVPg2AiK83K-rqS6AgmA: get metadata from youtube
tubearchivist  | [2024-08-10 15:33:43,153: WARNING/ForkPoolWorker-4] WARNING: [youtube] Falling back to generic n function search
tubearchivist  |          player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
tubearchivist  | [2024-08-10 15:33:43,168: WARNING/ForkPoolWorker-4] WARNING: [youtube] BpPVh4UK6oo: nsig extraction failed: Some formats may be missing
tubearchivist  |          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
tubearchivist  |          n = XXPDd7hT3OPimungi ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
tubearchivist  | [2024-08-10 15:33:43,171: WARNING/ForkPoolWorker-4] WARNING: [youtube] BpPVh4UK6oo: nsig extraction failed: Some formats may be missing
tubearchivist  |          Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
tubearchivist  |          n = cPuGkyGQSl7F2IzM5 ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
tubearchivist  | [2024-08-10 15:33:44,342: WARNING/ForkPoolWorker-4] UC6izVPg2AiK83K-rqS6AgmA: download channel thumbnail
tubearchivist  | [2024-08-10 15:33:50,497: WARNING/ForkPoolWorker-4] 38834140-c0b6-4450-bad0-e497e73f3932 success callback
tubearchivist  | [2024-08-10 15:33:50,499: INFO/ForkPoolWorker-4] Task subscribe_to[38834140-c0b6-4450-bad0-e497e73f3932] succeeded in 10.054632317s: None
tubearchivist  | [2024-08-10 15:33:50,499: WARNING/ForkPoolWorker-4] 38834140-c0b6-4450-bad0-e497e73f3932 return callback
```

You see the *n function* errors, but that is usually not fatal and will be fixed with a yt-dlp update.

Situations like that, where people experience problems that can't be reproduced by others, it's usually when people get blocked by YT. Who knows what kind of pattern detection they employ.

**Closed** 2024-08-25 13:26 UTC
Labels: invalid
