### ISSUE TITLE
[Bug]: Task failed: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by aandy717** [tubearchivist/tubearchivist#508] opened 2023-08-05 16:33 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

linuxmint 

## Describe the bug
When I add a playlist in "add to download queue" it does not work, I get the message: Task failed: 'bool' object has no attribute 'get'. 
If I add a single video link it works.

## Steps To Reproduce
copy a youtube playlist link and copy it to downloads
## Expected behavior
Tube archivist should add all files from the playlist to the downloads queue

Thanks
Andrea

### Relevant log output

```shell
[2023-08-05 18:24:01,571: WARNING/ForkPoolWorker-2] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:04,690: WARNING/ForkPoolWorker-2] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:04,691: WARNING/ForkPoolWorker-2] WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[2023-08-05 18:24:09,016: WARNING/ForkPoolWorker-2] 5AetLharQG8: get metadata from youtube
[2023-08-05 18:24:09,540: WARNING/ForkPoolWorker-2] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:10,875: WARNING/ForkPoolWorker-2] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:10,876: WARNING/ForkPoolWorker-2] WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[2023-08-05 18:24:11,966: WARNING/ForkPoolWorker-2] UCc1rCqLy7bf-j8Xr5e5ExIA: get metadata from es
[2023-08-05 18:24:12,061: WARNING/ForkPoolWorker-2] 5AetLharQG8-en: get user uploaded subtitles
[2023-08-05 18:24:12,061: WARNING/ForkPoolWorker-2] 5AetLharQG8-en: get auto generated subtitles
[2023-08-05 18:24:12,061: WARNING/ForkPoolWorker-2] 5AetLharQG8-it: get user uploaded subtitles
[2023-08-05 18:24:12,061: WARNING/ForkPoolWorker-2] 5AetLharQG8-it: get auto generated subtitles
[2023-08-05 18:24:15,373: WARNING/ForkPoolWorker-2] UCTsM1dSAiXqiV5oZjuNw_Bg: index all playlists
[2023-08-05 18:24:15,373: WARNING/ForkPoolWorker-2] UCTsM1dSAiXqiV5oZjuNw_Bg: get metadata from es
[2023-08-05 18:24:16,049: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:16,050: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-08-05 18:24:16,611: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:16,611: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-08-05 18:24:17,125: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:17,125: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-08-05 18:24:17,643: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:24:17,644: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-08-05 18:24:17,647: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] UCTsM1dSAiXqiV5oZjuNw_Bg: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-08-05 18:24:17,647: WARNING/ForkPoolWorker-2] https://www.youtube.com/channel/UCTsM1dSAiXqiV5oZjuNw_Bg/playlists?view=1&sort=dd&shelf_id=0: failed to get info from youtube with message ERROR: [youtube:tab] UCTsM1dSAiXqiV5oZjuNw_Bg: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-08-05 18:24:17,651: WARNING/ForkPoolWorker-2] 8af4f06d-9f15-4cb4-9bb9-74c22e8cf823 Failed callback
[2023-08-05 18:24:17,654: ERROR/ForkPoolWorker-2] Task download_pending[8af4f06d-9f15-4cb4-9bb9-74c22e8cf823] raised unexpected: TypeError("'bool' object is not subscriptable")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 205, in download_pending
    videos_downloaded = downloader.run_queue(auto_only=auto_only)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/download/yt_dlp_handler.py", line 192, in run_queue
    DownloadPostProcess(self).run()
  File "/app/home/src/download/yt_dlp_handler.py", line 42, in run
    self.validate_playlists()
  File "/app/home/src/download/yt_dlp_handler.py", line 101, in validate_playlists
    channel.index_channel_playlists()
  File "/app/home/src/index/channel.py", line 242, in index_channel_playlists
    self.get_all_playlists()
  File "/app/home/src/index/channel.py", line 312, in get_all_playlists
    all_entries = [(i["id"], i["title"]) for i in playlists["entries"]]
                                                  ~~~~~~~~~^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
[2023-08-05 18:24:17,666: WARNING/ForkPoolWorker-2] 8af4f06d-9f15-4cb4-9bb9-74c22e8cf823 return callback
query words: ['trai']
query_map: {'term': [], 'fuzzy': [], 'index': 'ta_video,ta_channel,ta_playlist'}
es path: ta_video,ta_channel,ta_playlist/_search
query: {'size': 30, 'query': {'bool': {'must': [{'multi_match': {'query': 'trai', 'type': 'bool_prefix', 'fuzziness': 'auto', 'operator': 'and', 'fields': ['channel_name._2gram', 'channel_name._3gram', 'channel_name.search_as_you_type', 'playlist_name._2gram', 'playlist_name._3gram', 'playlist_name.search_as_you_type', 'title._2gram', 'title._3gram', 'title.search_as_you_type']}}]}}}
query words: ['train']
query_map: {'term': [], 'fuzzy': [], 'index': 'ta_video,ta_channel,ta_playlist'}
es path: ta_video,ta_channel,ta_playlist/_search
query: {'size': 30, 'query': {'bool': {'must': [{'multi_match': {'query': 'train', 'type': 'bool_prefix', 'fuzziness': 'auto', 'operator': 'and', 'fields': ['channel_name._2gram', 'channel_name._3gram', 'channel_name.search_as_you_type', 'playlist_name._2gram', 'playlist_name._3gram', 'playlist_name.search_as_you_type', 'title._2gram', 'title._3gram', 'title.search_as_you_type']}}]}}}
query words: ['train', 'lik']
query_map: {'term': [], 'fuzzy': [], 'index': 'ta_video,ta_channel,ta_playlist'}
es path: ta_video,ta_channel,ta_playlist/_search
query: {'size': 30, 'query': {'bool': {'must': [{'multi_match': {'query': 'train lik', 'type': 'bool_prefix', 'fuzziness': 'auto', 'operator': 'and', 'fields': ['channel_name._2gram', 'channel_name._3gram', 'channel_name.search_as_you_type', 'playlist_name._2gram', 'playlist_name._3gram', 'playlist_name.search_as_you_type', 'title._2gram', 'title._3gram', 'title.search_as_you_type']}}]}}}
query words: ['train', 'like']
query_map: {'term': [], 'fuzzy': [], 'index': 'ta_video,ta_channel,ta_playlist'}
es path: ta_video,ta_channel,ta_playlist/_search
query: {'size': 30, 'query': {'bool': {'must': [{'multi_match': {'query': 'train like', 'type': 'bool_prefix', 'fuzziness': 'auto', 'operator': 'and', 'fields': ['channel_name._2gram', 'channel_name._3gram', 'channel_name.search_as_you_type', 'playlist_name._2gram', 'playlist_name._3gram', 'playlist_name.search_as_you_type', 'title._2gram', 'title._3gram', 'title.search_as_you_type']}}]}}}
[2023-08-05 18:32:13,384: INFO/MainProcess] Task extract_download[0881f844-eda9-4cb4-823d-4cc815af91b1] received
[2023-08-05 18:32:13,385: WARNING/ForkPoolWorker-2] extract_download create callback
[2023-08-05 18:32:14,060: WARNING/ForkPoolWorker-2] PL1FaSJSDBzH72exlc3pQjsabDrMHa609K: get metadata from es
[2023-08-05 18:32:14,069: WARNING/ForkPoolWorker-2] {"_index":"ta_playlist","_id":"PL1FaSJSDBzH72exlc3pQjsabDrMHa609K","found":false}
[2023-08-05 18:32:14,069: WARNING/ForkPoolWorker-2] PL1FaSJSDBzH72exlc3pQjsabDrMHa609K: get metadata from youtube
[2023-08-05 18:32:14,830: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:32:14,830: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-08-05 18:32:15,330: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:32:15,331: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-08-05 18:32:15,821: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:32:15,821: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-08-05 18:32:16,333: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-05 18:32:16,334: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-08-05 18:32:16,337: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] PL1FaSJSDBzH72exlc3pQjsabDrMHa609K: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-08-05 18:32:16,337: WARNING/ForkPoolWorker-2] https://www.youtube.com/playlist?list=PL1FaSJSDBzH72exlc3pQjsabDrMHa609K: failed to get info from youtube with message ERROR: [youtube:tab] PL1FaSJSDBzH72exlc3pQjsabDrMHa609K: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-08-05 18:32:16,346: WARNING/ForkPoolWorker-2] 0881f844-eda9-4cb4-823d-4cc815af91b1 Failed callback
[2023-08-05 18:32:16,348: ERROR/ForkPoolWorker-2] Task extract_download[0881f844-eda9-4cb4-823d-4cc815af91b1] raised unexpected: AttributeError("'bool' object has no attribute 'get'")
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 223, in extrac_dl
    pending_handler.parse_url_list()
  File "/app/home/src/download/queue.py", line 182, in parse_url_list
    self._process_entry(entry)
  File "/app/home/src/download/queue.py", line 199, in _process_entry
    self._parse_playlist(entry["url"])
  File "/app/home/src/download/queue.py", line 232, in _parse_playlist
    video_results = playlist.json_data.get("playlist_entries")
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
[2023-08-05 18:32:16,361: WARNING/ForkPoolWorker-2] 0881f844-eda9-4cb4-823d-4cc815af91b1 return callback
```

**Comment by bbilly1** [comment] 2023-08-06 03:43
I can't reproduce that. Your error suggests that you couldn't extract the playlist `PL1FaSJSDBzH72exlc3pQjsabDrMHa609K`. That works fine for me, matter of fact, all playlists from that channel extract fine.

Maybe that's a temporary hiccup on yt side? or yt-dlp?

**Comment by lamusmaser** [comment] 2023-08-06 19:18
Based on the way that I'm reading the error, I would actually say that this is not being caused by the playlist ID indicated, as that one is successfully being reviewed. This seems to be failing during the `get_all_playlists` function, so it is actually whichever playlist is after that one (or a few later) that is failing. I checked that specific channel, but it doesn't seem to be caused by any of those. Doesn't look like there is anything detailing which channel is being reviewed during this check, either.

I think this is some kind of bug, but it could very well be an issue on either the YT or yt-dlp side - do you think we should find a better way to handle it or should we let it just fail the process?

**Comment by bbilly1** [comment] 2023-08-12 02:23
closing this as not able to reproduce.

**Closed by bbilly1** 2023-08-12 02:23 UTC
Labels: question
