### ISSUE TITLE
[Installation]: tubearchivist-es crashes - ARM support request

### ISSUE THREAD

**Issue by LoganJFisher** [tubearchivist/tubearchivist#691] opened 2024-04-02 02:32 UTC
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Synology

### Your installation or setup question

I have followed [these](https://docs.tubearchivist.com/installation/synology/) instructions (granted, using Synology Container Manager, but it should be fully backwards compatible to support these instructions).

I've redone the steps to set up that container twice, but I keep having this issue. Can anyone suggest how to resolve this? Thanks.

### Relevant log output

```Shell
exec /bin/tini: exec format error
```

**Comment by LoganJFisher** [comment] 2024-04-02 03:39
It seems this may be because my Synology NAS is on ARM rather than x86. While redis/redis-stack-server and bbilly1/tubearchivist both have ARM support, it seems that bbilly1/tubearchivist-es is only available for x86.

Would it be too big of a request for ARM support to be added?

**Comment by trafficman** [comment] 2024-04-02 03:52
The default docker compose installation [mentions using the official Elasticsearch image instead for ARM support](https://docs.tubearchivist.com/installation/docker-compose/#elasticsearch), perhaps the Synology installation guide should mention it as well if they make NAS appliances that are ARM based

**Comment by LoganJFisher** [comment] 2024-04-02 03:58
Ah, thank you! I'll check out those instructions and will hopefully have better luck.

Yes, most of their systems are x86 based, but there are a handful of ARM based ones. For example, I have the [Synology DS423](https://www.synology.com/en-us/products/DS423#features), which is ARM based. The Synology instructions should definitely be updated not just to include this, but that Synology now uses the Synology Container Manager - while backwards compatible with all of the same settings, things are just organized a little differently.

**Comment by lamusmaser** [comment] 2024-04-02 04:33
I did not originally need to consider the ARM versions when drafting the documentation, but we can add a note. I'm doing a full documentation review, so I can include that note. 

I am aware of the Synology 7.2+ changes to the Synology Container Manager, but I haven't completed my testing at this time due to other efforts requiring my focus and effort. Those additional updates and changes will be incorporated, but meanwhile I can confirm that the existing instructions backport in just fine.

**Comment by LoganJFisher** [comment] 2024-04-02 04:43
I think I'll have to wait until this documentation update then, as I'm having difficulty with running the normal Elastisearch container too. Instructions on its install as part of the process of setting up Tube Archivist (rather than referring to external documentation) would be incredibly helpful. Like it's unclear to me if any environment variables still need to be added. Regardless of if they do, my Elastisearch container is crashing with log "exec /docker-entrypoint.sh: exec format error", but that's a matter to discuss with the Elastisearch devs on their Github repository, not with you all.

Thanks for the support. :)

**Comment by lamusmaser** [comment] 2024-04-02 05:00
Should be the same instructions, just swapping 2.b.ES from `bbilly1/tubearchivist-es` to `docker.elastic.co/elasticsearch/elasticsearch`.

If that doesn't work, let me know and I'll review more later.

**Comment by LoganJFisher** [comment] 2024-04-02 05:05
I'm afraid I don't follow. What is 2.b.ES?

**Comment by lamusmaser** [comment] 2024-04-02 05:10
In the already documented instructions: https://docs.tubearchivist.com/installation/synology/#2-install-docker-images

**Comment by LoganJFisher** [comment] 2024-04-02 05:14
Oh, you were referring to a part of the documentation. Sorry, I wasn't sure what you were referring to.

Alright, I'll check in with the Elastisearch Github regarding the issue I'm having with creating that container. Once I have that sorted, I'll give an update here on if I'm able to get the other aspects of the Tube Archivist setup to work properly.

**Comment by LoganJFisher** [comment] 2024-04-05 21:07
Well, I'm having no luck finding support from Elastisearch. I didn't want to trouble you with an issue happening with them, but I suppose this is the next best place to ask. Sorry.

I'm really at a loss for what is going wrong. Here's some screenshots of everything:

[error log](https://i.imgur.com/FVbtwEe.png)

[settings 1](https://i.imgur.com/f1tISAw.png)
[settings 2](https://i.imgur.com/fLtmO3c.png)
[settings 3](https://i.imgur.com/F0DXOeA.png)

I appreciate any help you can provide on this. Sorry again.

**Comment by bbilly1** [comment] 2024-04-05 21:17
Also share a clean set of docker logs from ES container start until the error. preferably in text not as screenshot.

Also it's not visible from your screen shots, but double check that you are using official ES and not the AMD rebuild. Sometimes things can be funky with these alternative docker frontends, so to make sure, I'd say take all down, remove ES container and image, then make sure the image you pull is the official one.

Also looks like your Synology only has 2GB of ram, that might not be enough. Especially depending on what else you have running there.

**Comment by LoganJFisher** [comment] 2024-04-05 21:29
That is a clean set of docker logs from the ES container from start until the error. There simply is nothing else.

> exec /docker-entrypoint.sh: exec format error

Confirmed that it's the [official ES](https://registry.hub.docker.com/_/elasticsearch/).

Maybe there's a RAM issue. I'm idling at 48% usage and it only seemed to go up to 49% when trying to run this container.

**Comment by bbilly1** [comment] 2024-04-05 21:37
If you are sure about that this is the official ES image running, then nothing else we can do here.

Others using ARM 64 bit hardware like some mac devices or Pis or similar, are able to run this by making these changes as documented. If that is not the case with your hardware, then it looks like this isn't compatible with your hardware. 

Sorry.

**Closed** 2024-04-05 21:40 UTC
Labels: invalid

**Comment by LoganJFisher** [comment] 2024-04-05 21:57
Oh, last-ditch effort: I see that there's an Elastisearch server addon for Home Assistant (which I'm running on my RPi4), which shows as compatible. Would it be possible to set that up there and then still connect to the Docker containers for Tubearchivist itself on my Synology NAS instead?

**Comment by bbilly1** [comment] 2024-04-05 22:04
You could run ES on your pi, as long as it's 64 bit, expose it in your LAN and have TA on your synology connect to it, that's a matter of networking.

Or run all of it on your PI. But honestly, performance is not great, it's not built for these low end devices.
