### ISSUE TITLE
[Bug]: Rescanning subscriptions doesn't actually rescan playlists properly

### ISSUE THREAD

**Issue by DutchEllie** [tubearchivist/tubearchivist#518] opened 2023-08-17 11:53 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

I try to use Tube Archivist as a way to archive playlists on Youtube that I make. Because of this, I keep adding videos in the playlists on Youtube and I am also subscribed to those playlists in Tube Archivist. 
However, when I press rescan subscriptions on the downloads page, the playlists aren't properly rescanned and the newly added videos aren't added to the download queue. 

## Steps To Reproduce

1. Download a youtube playlist and add it to your subscriptions in TA
2. Add a new video to the playlist on Youtube
3. Rescan subscriptions
4. Doesn't add new videos

## Expected behavior

It should just add the new videos when it rescans the playlist. 

### Relevant log output

```shell
[2023-08-17 13:48:13,395: WARNING/ForkPoolWorker-8] PLmW1M4_Vx0QwNCmmTRoFlwF9rEBNDqlhu: get metadata from es
[2023-08-17 13:48:13,405: WARNING/ForkPoolWorker-8] PLmW1M4_Vx0QwNCmmTRoFlwF9rEBNDqlhu: get metadata from youtube
[2023-08-17 13:48:13,637: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-17 13:48:13,637: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[2023-08-17 13:48:13,792: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-17 13:48:13,792: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[2023-08-17 13:48:13,925: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-17 13:48:13,925: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[2023-08-17 13:48:14,061: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-08-17 13:48:14,062: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[2023-08-17 13:48:14,063: WARNING/ForkPoolWorker-8] ERROR: [youtube:tab] PLmW1M4_Vx0QwNCmmTRoFlwF9rEBNDqlhu: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
[2023-08-17 13:48:14,063: WARNING/ForkPoolWorker-8] https://www.youtube.com/playlist?list=PLmW1M4_Vx0QwNCmmTRoFlwF9rEBNDqlhu: failed to get info from youtube with message ERROR: [youtube:tab] PLmW1M4_Vx0QwNCmmTRoFlwF9rEBNDqlhu: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
```

### Anything else?

![image](https://github.com/tubearchivist/tubearchivist/assets/6501187/c3e6712b-f542-4798-88dc-e672faf8c906)

This is a screenshot of the playlist I am mainly referring to that is having this mistake. After a reindex, it even shows up as "deactivated"! 
![image](https://github.com/tubearchivist/tubearchivist/assets/6501187/2babea5c-2ca4-41ac-ab61-7cb3e883da24)

**Comment by DutchEllie** [comment] 2023-08-17 12:02
Okay, so that last part about it becoming "Deactivated" is I think just Tube Archivist losing the cookie or something. Reimporting the cookie fixed that, but it doesn't fix the other issues.

**Comment by DutchEllie** [comment] 2023-08-17 12:13
One last comment with more context before I just leave it to you guys. Increasing the "Channel Page Size" in the settings allowed me to download more videos, but it still doesn't actually work like intended (or I can't possibly imagine why it would).
I increased it to 60 and the new videos were downloaded. However, I didn't add more than 50 videos to the playlist since last time I downloaded the playlist. So it makes no sense that it wouldn't find the videos. 

Another playlist with over 200 videos shows this somewhat. After performing a rescan and a download with the page size set to 60, it has 61 videos (I believe on youtube one was deleted, which is exactly why I use tubearchivist). It did add the newest videos, but I can't trust this system like this, something is definitely broken.

**Comment by bbilly1** [comment] 2023-08-17 12:34
Can't access that, as it's private. Maybe related to #171? If your cookie doesn't work, you could also try to set the playlist as unlisted.

You can also see a bunch of `Incomplete yt initial data received` error messages from yt-dlp there.

**Comment by K1Hyve** [comment] 2023-08-23 14:07
I also had this issue and removing some of the videos from the playlist and reducing it from 61 to 30 fixed the issue and videos added to download list. I'm not using cookies and my playlist is unlisted.

**Comment by bbilly1** [comment] 2023-09-03 06:21
closing this due to lack of info.

**Closed by bbilly1** 2023-09-03 06:21 UTC
Labels: question

**Comment by K1Hyve** [comment] 2023-09-03 19:08
This happened to me a few days ago with my playlist having more than 50 items and it couldn't download it and reducing the size to below that fixed it immediately

**Comment by sehv** [comment] 2023-10-08 01:08
I've been bit hard by this. 24 playlists currently subscribed to, only four can be updated. It doesn't appear to be a TA bug, though: https://github.com/yt-dlp/yt-dlp/issues/8206

The size-reduction workaround isn't really a fix, but it bypasses the root of the issue. Unfortunately, it doesn't work in all cases (I've got a couple playlists with fewer than ten videos, so they are already well below the DL limit already).

YT may eventually fix it on their end, or you could probably force TA to use the latest version from PyPI (2023.10.7) until a new TA release comes out (haven't tried it yet).

**Comment by Starwalker98** [comment] 2023-10-11 21:05
I actually have the same issue. What I need to do, is remove the cookies, save, enable cookies, save, and reindex the playlist. It will then say Active again, and let me download new additions. Unfortunately, this also means that I have to manually reindex every single playlist,, but it is a workaround

**Comment by sehv** [comment] 2023-10-13 03:29
Forcing an update to yt-dlp 2023.10.7 fixed the issue for me. Though it looks like at the same time I was experimenting with that, TA 0.4.2 was released which also bumps the yt-dlp version, so upgrading should resolve the issue.

I also needed to manually re-index each of the affected playlists before it saw them as Active again, but the re-indexing is thankfully a pretty quick process.

**Comment by Starwalker98** [comment] 2023-10-17 12:23
The issue is still unfortunately present for me even on 0.4.2

**Comment by whitedemong** [comment] 2024-05-01 09:29
The problem persists.

OS: UnRaid 6.12.10
TubeArchivist version: 0.4.7.

Scenario:
1 - subscribing to a Playlist
2 - I do "Rescan subscriptions"
3 - all the videos from the Playlist appear.
4 - I download all videos by clicking on "Start download".
5 - Everything goes correctly
6 - a new video appears on the channel and it is added to the previously subscribed Playlist.
7 - Scheduler does not detect the new video
8 - I go to "Downloads" section
9 - I do "Rescan subscriptions"
10 - new video does not appear
11 - I go to "Playlist" section, to Specific Playlist. 
12 - click "Reindex".
13 - I go to "Downloads"
14 - I do "Rescan subscriptions"
15 - The new video appears in the Download Queue and can be downloaded.

Perhaps this problem is solved through Settings and adding your own cookie - I haven't tried.

But why is it not possible to perform the same actions for Playlists when "Rescan subscriptions" or using the Scheduler as when adding a Playlist or performing a Reindex? 
For example, Reindex should be done automatically or the part of the Code that is executed when adding a new Playlist or Reindex?

Thanks in advance.
