### ISSUE TITLE
[Feature Request]: Gradual archiving of channels

### ISSUE THREAD

**Issue by seelenamt** [tubearchivist/tubearchivist#759] opened 2024-07-08 17:25 UTC
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

Trying to archive an entire channel on Tube Archivist currently requires you to set the page size to >50 (or at least, that’s my understanding).

At that point, everything added will be added to the cue and downloaded, which isn’t ideal for users who are trying to archive entire channels but are unfortunate enough to have ISPs who impose stringent data caps. 

As far as I know, the only way around this would be to manually increase the page size a few at a time, or to throttle the download speed appropriately. Another option might be to manually create playlists and feed them into Tube Archivist a few at a time

## Describe the solution you'd like

Add an option where for every new video a certain number videos are grabbed as well. 

I’m not familiar enough with the limits of page sizes to know if this would work, but an option where when new videos are detected the page size is dynamically increased by the number of new videos + a number of old videos (chosen by the user) to add

e.g. the user has a page size of 20. They set it so that for every new video, two older videos are downloaded. A new video is found, and the page size is increased to 23.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by Thrilleratplay** [comment] 2024-07-11 11:24
I am new to TubeArchivist but I ran into a similar issue.  This may be a indirect duplicate of #189

**Comment by bbilly1** [comment] 2024-07-12 15:25
Yes, as mentioned, more or less a duplicate.

**Closed by bbilly1** 2024-07-12 15:25 UTC
Labels: duplicate
