### ISSUE TITLE
[Bug]: "Reindex Documents" task hung

### ISSUE THREAD

**Issue by lue30499** [tubearchivist/tubearchivist#631] opened 2023-12-12 23:52 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux with docker

## Describe the bug
In the dashboard, the "Reindex Documents" task get stuck. Every time it runs it doesn't seem to finish and the task list builds up.

## Steps To Reproduce
Not sure, I seems specific to my setup.

## Expected behavior
The "Reindex Documents" task to finish

### Relevant log output

```shell
My log was took long for github. Attached below ( ta_logs.txt ).
```

### Anything else?

<img width="1190" alt="Screenshot 2023-12-10 at 07 54 41" src="https://github.com/tubearchivist/tubearchivist/assets/63104612/8078a195-c5a8-4283-bf1d-b23a524cf94a">

[ta_logs.txt](https://github.com/tubearchivist/tubearchivist/files/13654281/ta_logs.txt)

**Comment by bbilly1** [comment] 2023-12-16 08:42
What are the exit status of these tasks? You can get an overview through the API at: `/api/task-name/check_reindex/` or by ID: `/api/task-id/<task-id>/`.

**Comment by lue30499** [comment] 2023-12-16 10:05
Hi @bbilly1 

Currently, the dashboard looks like this:

<img width="974" alt="Screenshot 2023-12-16 at 21 02 44" src="https://github.com/tubearchivist/tubearchivist/assets/63104612/69ac1c60-79cd-4213-abcd-4cf7aa333b5b">

Running:
```
curl -H "Authorization: Token <token>" http://<domain>/api/task-name/check_reindex/
[
  {
    "status": "SUCCESS",
    "result": "reindexed 284 videos, 2 channels",
    "traceback": null,
    "children": [],
    "date_done": "2023-12-15T12:09:36.149983",
    "name": "check_reindex",
    "args": [],
    "kwargs": {},
    "worker": "celery@18ad8dfd4035",
    "retries": 0,
    "queue": "celery",
    "task_id": "f0308d02-e0ea-486f-8091-1b8a195d96f2"
  }
]
```

Looks as though the dashboard is out of sync with the task???

**Comment by bbilly1** [comment] 2023-12-16 10:19
Looks like these task results already expired. You'd might want to monitor that and run that API request again, within 24h (I think) after a task fails.

But it looks like these notifications just got stuck, assuming because of a bug in celery, the task queue management library. That's fixed by downgrading the redis python library, at least for now: https://github.com/tubearchivist/tubearchivist/commit/6f1a45ffb1c1434c26f435c6d1c0d195be3f51b7, assuming that this never triggers the failed callback, preventing the clean up and error message of the failed task.

**Comment by bbilly1** [comment] 2023-12-21 04:17
any additional insights? Also v0.4.5 brings a fix for the celery error you see in your logs.

**Comment by lue30499** [comment] 2023-12-26 06:31
I have updated to v0.4.5 I'll see if it fixes it.
If not, I'll add some more logs.

**Comment by lamusmaser** [comment] 2024-01-05 17:16
Checking in with @lue30499 to confirm if this is now resolved for you.

**Comment by lue30499** [comment] 2024-01-05 17:29
Hello, thanks for the nudge... I did forget.

The issues don't seem to be damaging in any way (and a restart of the tubearchivet container clears it). I also use TA to archive, so I don't look at it daily.

The issue is persisting, even on v0.4.5:
Screenshot and logs from now (Jan 6th):
<img width="1301" alt="Screenshot 2024-01-06 at 04 17 48" src="https://github.com/tubearchivist/tubearchivist/assets/63104612/ee73e4ef-823b-47b1-9021-aece3c835056">


[ta_logs-240106.txt](https://github.com/tubearchivist/tubearchivist/files/13844862/ta_logs-240106.txt)


Regards,
Lue

**Comment by lamusmaser** [comment] 2024-01-05 18:30
This still seems to be an issue of something getting stuck in the message handler. I am looking at the logs and seeing jobs start, complete, and then close. So, this is something that is happening just in the Redis messaging that isn't clearing those messages for you. 

Based on the [previous items](https://github.com/tubearchivist/tubearchivist/issues/631#issuecomment-1858782234) in the thread, I would say that you should look at reverting the Redis version and see if that allows it to work as expected.

**Comment by lue30499** [comment] 2024-01-05 18:35
Hi @lamusmaser ,

I am running redis/redis-stack-server:6.2.6-v9
What version do I go back to? ( I didn't upgrade to 7.x.x due to #517 )

Regards,
Lue.

**Comment by bbilly1** [comment] 2024-03-11 17:25
I don't see how this can happen. Closing this due to lack of reproducibility.

**Closed by bbilly1** 2024-03-11 17:25 UTC
Labels: invalid
