### ISSUE TITLE
[Installation]: 

### ISSUE THREAD

**Issue by piptravels** [tubearchivist/tubearchivist#444] opened 2023-03-04 15:40 UTC
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Distributor ID:	Ubuntu Description:	Ubuntu 22.04.2 LTS Release:	22.04 Codename:	jammy

### Your installation or setup question

I setup docker, fully update (nothing else installed) and used the docker-compose.yml (changed the info suggested) and everything went fine until the es container:
Creating archivist-es ... error

ERROR: for archivist-es  Cannot start service archivist-es: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown

ERROR: for archivist-es  Cannot start service archivist-es: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.

Due to my extreme ignorance (not in IT-just learning selfhosting, docker, etc) I'm not sure how to troubleshoot as I don't know where to look for useful information. I did a search on the error but my lack of context to understand possible solutions has me unsure what to try as a solution. 

Any help would be great appreciated

### Relevant log output

```shell
eric@tubearchivist:~/tubearchivist$ docker-compose logs
Attaching to archivist-es
```

**Comment by lamusmaser** [comment] 2023-03-04 15:58
This would normally be handled by the `ulimits` condition set for the ES container. Are you able to paste your sanitized `docker-compose` or upload it to somewhere that can allow us to review it?

**Comment by piptravels** [comment] 2023-03-04 16:23
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.local         # set your host name
      - TA_USERNAME=eric           # your initial TA credentials
      - TA_PASSWORD=xxxxxxxxxxx              # your initial TA credentials
      - ELASTIC_PASSWORD=xxxxxxxxxxx         # set password for Elasticsearch
      - TZ=America/Chicago                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.6.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=xxxxxxxxxxx"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:

**Comment by lamusmaser** [comment] 2023-03-04 16:35
It doesn't look like it formatted properly, but the expected configurations are present - if you copied it and just made minor modifications, then it should read through properly with the correct spacing.

I guess first, are you running this as either the docker user, root, or another user? This could cause this type of error if the user doesn't have permission to start the containers. Second, let's make sure that the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) are handled.

**Comment by piptravels** [comment] 2023-03-04 16:36
I installed docker and docker-compose as root then added myself as a user gave myself sudo and the usermod -aG docker eric

**Comment by piptravels** [comment] 2023-03-04 16:40
root@tubearchivist:~# sudo sysctl -w vm.max_map_count=262144
sysctl: permission denied on key "vm.max_map_count", ignoring

**Comment by piptravels** [comment] 2023-03-04 16:50
this is how I created it (the server instance) lxc launch ubuntu:22.04 tubearchivist --profile default --profile bridgeprofile -c boot.autostart=true -c security.nesting=true  -c limits.memory=4096MB -c limits.cpu.allowance=20%

**Comment by bbilly1** [comment] 2023-03-04 16:50
I've seen some similar problems from people running nested virtualization. You can try to remove the `ulimits` section from the ElasticSearch container, basically not set this part here: https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml#L46-L49

Some virtualization software might not support these configurations. 

The vm.max_map_count is discribed in the common error sections here: https://github.com/tubearchivist/tubearchivist#vmmax_map_count but that might not be a breaking change.

**Comment by lamusmaser** [comment] 2023-03-04 16:50
Ah, yeah, that would be it. I can see in [here](https://serverfault.com/a/798046) that there are issues with a container attempting to run ElasticSearch as an internal container. So, while not exactly the same, I would expect the principles to be the same.

So, my recommendation would be to attempt to see if we could setup the TA containers on LXD itself, but that hasn't been documented at this point in time.

So, I would definitely say that we could get that handled there.

**Comment by piptravels** [comment] 2023-03-04 16:59
not sure what TA containers are but I would like to learn

**Comment by lamusmaser** [comment] 2023-03-04 17:01
Absolutely, that would be each of the TubeArchivist containers that the docker-compose attempts to start: `tubearchivist`, `redis`, and `elasticsearch`. Each container runs some function within the overall system that allows TubeArchivist to run properly.

**Comment by lamusmaser** [comment] 2023-03-04 17:05
Looking into it [a bit further](https://github.com/lxc/lxd/issues/4166), it looks like LXD would not support a docker-compose style method, so we'd have to create the containers individually.

So, we'll have either:
1. Set you up with docker/docker-compose on your primary system so that it can run these containers without nesting.
2. Attempt to run it with the configurations suggested by @bbilly1, which might allow it to run.
3. We work to attempt to determine how to start the containers via LXD and run through that process.

Let me know your preference and we can work on determining the best path forward. 2 is potentially the fastest, 1 would be the most supported, 3 would potentially require the least changes to your environment, but could require additional long-term maintenance.

**Comment by piptravels** [comment] 2023-03-04 17:05
I also have an Umbrel Pi4 server, a Proxmox old laptop server, a CasaOS Zimaboard, would it be easier to try installing TA on one of those? I just want to use TA, not really concerned which way it happens

**Comment by lamusmaser** [comment] 2023-03-04 17:06
> I also have an Umbrel Pi4 server, a Proxmox old laptop server, a CasaOS Zimaboard, would it be easier to try installing TA on one of those? I just want to use TA, not really concerned which way it happens

See my last post, we can definitely have it setup with (1) and see if that would allow you to run TA successfully.

**Comment by piptravels** [comment] 2023-03-04 17:07
so on my workstation laptop?

**Comment by lamusmaser** [comment] 2023-03-04 17:09
Anything that can run Docker will support it. The better the system, the easier it is to run long-term. We can definitely get it working from there depending on which platform you choose and it can run both Docker and compose.

**Comment by piptravels** [comment] 2023-03-04 17:10
I will try it on CasaOS then and report back shortly

**Comment by piptravels** [comment] 2023-03-04 17:33
I'm not sure how to fill this in to make it work
![11](https://user-images.githubusercontent.com/14855599/222920436-9388af2e-05b5-447f-85a8-2534f7f923b9.png)
![12](https://user-images.githubusercontent.com/14855599/222920443-8445e794-bb79-4fbe-bdf3-b306ff2eb500.png)

**Comment by lamusmaser** [comment] 2023-03-04 17:37
This should have fairly similar configurations to using [Synology's docker configuration manager](https://github.com/tubearchivist/tubearchivist/wiki/Installation#docker-setup), so we'll use that as a baseline to help get the configurations.

If there is a specific question about any of the entries, ask and we'll figure out where it goes. I would recommend doing the same order, ElasticSearch -> Redis -> TubeArchivist.

**Comment by piptravels** [comment] 2023-03-04 17:56
so I'm creating volumes ElasticSearch, Redis, TubeArchivist? Is that correct?
and under environment variables:
 - ES_URL=http://archivist-es:9200 
 - REDIS_HOST=archivist-redis

**Comment by piptravels** [comment] 2023-03-04 17:59
not really sure about the values needed to add this
![16](https://user-images.githubusercontent.com/14855599/222921546-a7fd46a9-5a45-4838-9532-5bfe377f9794.png)

**Comment by lamusmaser** [comment] 2023-03-04 18:17
I'm writing a full description up, please give me some time to get all the details together.

**Comment by lamusmaser** [comment] 2023-03-04 18:43
Let's break things up to help you as best as possible:

### Before creating the containers
You'll need several volumes:
1 for ElasticSearch
1 for Redis
2 for TubeArchivist (one for cache, one for media)

These should be created first on the host. If you need help with these, let us know. You'll create them with the guided permissions, with the exception of ElasticSearch's volume's owner being `1000:0`.

### Note about "Ports"
In all of the container images, there is a "Web UI" section and a "Ports" section, both of which can supply external access. Because I am not as familiar with this application, we are going to try to forward through the Web UI section, but may need to modify these later to be in the "Ports" section.

### Note about "Passwords"
The TubeArchivist application will have a user and password that you will need to set. This will be used as the initial login user and password for the web frontend. Additionally, there is an `ELASTIC_PASSWORD` configuration that needs to be the same between the TubeArchivist and ElasticSearch container configurations.

### Container 1 - ElasticSearch
#### Docker Image
`bbilly1/tubearchivist-es`
#### App Name
`archivist-es`
#### Web UI
This can be set to `:9200` for the port section.
#### Network
`bridge`
#### Ports
Not required for this container setup.
#### Volumes
Host: `/dir/on/host/<es-volume>`
Container: `/usr/share/elasticsearch/data`
#### Environment Variables
Use the following for each variable, with `key` on the left, `value` on the right. There should be one `key`:`:value` pair per line.
Example:
`key=value`
Values to include:
```
discovery.type=single-node
ES_JAVA_OPTS=-Xms512m -Xmx512m
UID=1000
GID=0
xpack.security.enabled=true
ELASTIC_PASSWORD=verysecret
path.repo=/usr/share/elasticsearch/data/snapshot
```
#### Devices
Not required for this container setup.
#### Container Command
Not required for this container setup.
#### Privileged
No
#### Memory Limit
This should not have a memory limit.
#### CPU Shares
Set to your best guess. ES should have either a `low` or `medium` configuration.
#### Restart Policy
`always` will work for this container.
#### Container Capabilities
Not required for this container setup.
#### Container Hostname
Let it dynamically generate. If it is a required one, then you can supply `archivist-es`.
#### App Description
"ElasticSearch for TubeArchivist application".

### Container 2 - Redis
#### Docker Image
`redis/redis-stack-server`
#### App Name
`archivist-redis`
#### Web UI
This can be set to `:6379` for the port section.
#### Network
`bridge`
#### Ports
Not required for this container setup.
#### Volumes
Host: `/dir/on/host/<redis-volume>`
Container: `/data`
#### Environment Variables
Not required for this container setup.
#### Devices
Not required for this container setup.
#### Container Command
Not required for this container setup.
#### Privileged
No
#### Memory Limit
This should not have a memory limit.
#### CPU Shares
Set to your best guess. Redis should have a `low` configuration.
#### Restart Policy
`always` will work for this container.
#### Container Capabilities
Not required for this container setup.
#### Container Hostname
Let it dynamically generate. If it is a required one, then you can supply `archivist-redis`.
#### App Description
"Redis for TubeArchivist application".

### Container 3 - TubeArchivist
#### Docker Image
`bbilly1/tubearchivist`
#### App Name
`tubearchivist`
#### Web UI
This can be set to `:8000` for the port section.
#### Network
`bridge`
#### Ports
Not required for this container setup.
#### Volumes
##### Cache
Host: `/dir/on/host/<tubearhcivist-cache-volume>`
Container: `/cache`
##### Media
Host: `/dir/on/host/<tubearchivist-media-volume>`
Container: `/youtube`
#### Environment Variables
Use the following for each variable, with `key` on the left, `value` on the right. There should be one `key`:`:value` pair per line.
Example:
`key=value`
Values to include:
```
TA_HOST=tubearchivist.local 192.168.216.31
ES_URL=http://tubearchivist-es:9200
REDIS_HOST=tubearchivist-redis
HOST_UID=1000
HOST_GID=1000
TA_USERNAME=tubearchivist
TA_PASSWORD=verysecret
ELASTIC_PASSWORD=verysecret
TZ=America/New_York
```
#### Devices
Not required for this container setup.
#### Container Command
Not required for this container setup.
#### Privileged
No
#### Memory Limit
This should not have a memory limit.
#### CPU Shares
Set to your best guess. TubeArchivist should have either a `medium` or `high` configuration.
#### Restart Policy
`always` will work for this container.
#### Container Capabilities
Not required for this container setup.
#### Container Hostname
Let it dynamically generate. If it is a required one, then you can supply `tubearchivist`.
#### App Description
"Web Server for TubeArchivist application".

**Comment by piptravels** [comment] 2023-03-04 18:48
I will follow this and report back. I know that some people install docker apps outside the CasaOS interface for custom apps so worst case is I bork it and start over with a reinstall lol

**Comment by lamusmaser** [comment] 2023-03-04 18:51
Yep, and if we go that route, we'll probably just handle it via docker-compose. But let me know if you have questions or issues - I'll try to keep an eye on this today.

**Comment by piptravels** [comment] 2023-03-04 18:54
> Yep, and if we go that route, we'll probably just handle it via docker-compose. But let me know if you have questions or issues - I'll try to keep an eye on this today.

will do, my goal is to use TA and learn more about docker in general. I just sucks trying to search for solutions without enough context to know if they're a potential solution or not. You help is greatly appreciated

**Comment by piptravels** [comment] 2023-03-06 04:11
I tried to install TA on a VPS but was unable to login. I'm going to give the Synolgoy method a try and report back

**Comment by lamusmaser** [comment] 2023-03-06 04:23
If it looks like the applications are running, then it is probably just the one configuration under `TA_HOST` that needs adjusting. It should be set to however you are attempting to connect to the application; either an IP Address, hostname, or resolving DNS name for a domain. If you have more than one entity in the line, then it should be space delimited.

Examples below:
#### IP Only
```
TA_HOST=10.X.X.X
```
#### Hostname/Domain Only
```
TA_HOST=hostname.local
```
#### IP and Hostname/Domain
```
TA_HOST=10.X.X.X hostname.local
```

**Comment by piptravels** [comment] 2023-03-06 04:42
I had set a CNAME record for a subdomain for a domain I have that pointed
to the IP address of the VPS Server. Then when everything installed I went
to that subdomain and tried:

learn.link2view.com/8003 ( which is the port I set. Then tried it with
:8003 then with IP:8003 and nothing. I wish I knew more about this

**Comment by lamusmaser** [comment] 2023-03-06 04:47
Expecting that this was setup via a slightly modified Docker Compose setup, and that you are just pointing to the VPS directly via that subdomain, I would expect the following configurations:
#### Ports
```
- 8003:8000
```
#### TA_HOST
```
- TA_HOST=sub.domain.com
```
Then, the browser should point directly to that subdomain. If you don't have a reverse proxy in front of it, you would expect `http://learn.link2view.com:8003` to work.

**Comment by piptravels** [comment] 2023-03-06 04:54
That subdomain is proxied through Cloudflare so I thought https would be
the way to access it

**Comment by lamusmaser** [comment] 2023-03-06 05:04
HTTPS might be correct, it would depend on the CloudFlare configuration and if it is forcing E2E encryption for accessing it. This is where the specifics of the DNS configuration will be most important.

As a start, to confirm that it is working as intended, you could always just add the VPS IP address to the `TA_HOST` environment variable, then direct connect to it. Since that is going out over the Internet, I can also understand not wanting to do that and setting it up correctly from the get-go.

I would also ensure that DNS is resolving first - if you added the DNS entry within the past 24 hours, it could still be propagating and not allowing that subdomain to resolve properly. If you are comparing against `curl` command outputs, also note that `curl` and any of the browsers will have different methods for DNS resolution, so it may work on one side, but not the other, and you may just have to wait until you can actually use that subdomain.

**Comment by bbilly1** [comment] 2023-03-19 03:24
Due to lack of activity, assuming this has been solved by now. You can also reach out on discrod for any further assistance.

**Closed by bbilly1** 2023-03-19 03:24 UTC
Labels: question, installation
