### ISSUE TITLE
[Bug]: failed download keeps partial file in cache, failing following download.

### ISSUE THREAD

**Issue by kriss6557** [tubearchivist/tubearchivist#498] opened 2023-07-17 17:25 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 22.04.1 LTS / Docker version 20.10.22

## Describe the bug
Try to download this video (https://www.youtube.com/watch?v=Jl9lxBIK-3I)  and then get task failed.

## Steps To Reproduce
Add this channel (https://www.youtube.com/@tested) and try to download this video (https://www.youtube.com/watch?v=Jl9lxBIK-3I) and then it fails.

## Expected behavior
The video should download fine

### Relevant log output

```shell
[2023-07-17 19:13:47,008: INFO/MainProcess] Task download_pending[c4af06d6-6eb6-471f-8582-003c22ed53ef] received
[2023-07-17 19:13:47,010: WARNING/ForkPoolWorker-2] download_pending create callback
[2023-07-17 19:13:47,109: WARNING/ForkPoolWorker-2] Jl9lxBIK-3I: Downloading video
[2023-07-17 19:14:01,695: WARNING/ForkPoolWorker-2] Jl9lxBIK-3I: get metadata from youtube
[2023-07-17 19:14:05,926: WARNING/ForkPoolWorker-2] UCiDJtJKMICpb9B1qf7qjEOA: get metadata from es
[2023-07-17 19:14:05,954: WARNING/ForkPoolWorker-2] c4af06d6-6eb6-471f-8582-003c22ed53ef Failed callback
[2023-07-17 19:14:05,957: ERROR/ForkPoolWorker-2] Task download_pending[c4af06d6-6eb6-471f-8582-003c22ed53ef] raised unexpected: CalledProcessError(1, ['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/cache/download/Jl9lxBIK-3I.f251.webm.part'])
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 193, in download_pending
    VideoDownloader(task=self).run_queue(auto_only=auto_only)
  File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 430, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 157, in build_json
    self.add_player(media_path)
  File "/app/home/src/index/video.py", line 248, in add_player
    duration = duration_handler.get_sec(vid_path)
  File "/app/home/src/index/video_streams.py", line 16, in get_sec
    duration = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/cache/download/Jl9lxBIK-3I.f251.webm.part']' returned non-zero exit status 1.
```

**Comment by lamusmaser** [comment] 2023-07-17 17:29
Video is able to be downloaded successfully on my test instance. This usually means that there is something else happening. Can you confirm that you have enough space for the download, that the correct permissions are being applied, and what version of TubeArchivist you are currently running?

**Comment by kriss6557** [comment] 2023-07-17 19:04
Hi, 
Yes this is the only video that fails.
Storage is ok with 300G free.
All other videos have been saved successfully to the same location.
I'm using v0.3.6 (docker)

**Comment by lamusmaser** [comment] 2023-07-17 19:07
And has it only tried the one time and failed or is it still failing if you attempt to retry it now?

**Comment by lamusmaser** [comment] 2023-07-17 19:48
It should be getting cleared. I wonder if it had a partial file that was present from a previous download attempt which was interrupted.

Checking on the cache was going to be the next step, so good for getting that checked. I think we might be able to get some error handling out of this issue to see if we can catch it better (or provide more response).

Do you happen to have an output of what was in that cache before you deleted it (`ls` output, or something similar)?

**Comment by kriss6557** [comment] 2023-07-17 19:51
yes here it is:

```
-rw-r--r-- 1 root root    8387584 Jul 17 14:22 2AV9d8-VIrI.f313.webm.part-Frag61.part
-rw-r--r-- 1 root root  826885923 Jun 16  2021 2AV9d8-VIrI.mp4
-rw-r--r-- 1 root root    2096128 Jul 14 12:22 HH5x6kfVy2Y.f251.webm.part-Frag2.part
-rw-r--r-- 1 root root    8387584 Jul 14 12:16 HH5x6kfVy2Y.f313.webm.part-Frag122.part
-rw-r--r-- 1 root root    4193280 Jul 14 11:42 HH5x6kfVy2Y.f313.webm.part-Frag71.part
-rw-r--r-- 1 root root 1108237851 Oct 15  2022 HH5x6kfVy2Y.mp4
-rw-r--r-- 1 root root   88818536 Jun 30 05:02 Jl9lxBIK-3I.f248.webm
-rw-r--r-- 1 root root   95933637 Jun 30 04:34 Jl9lxBIK-3I.f248.webm.mp4
-rw-r--r-- 1 root root          0 Jul 15 17:05 Jl9lxBIK-3I.f251.webm.part
-rw-r--r-- 1 root root         50 Jul 15 17:05 Jl9lxBIK-3I.f251.webm.ytdl

```

**Comment by lamusmaser** [comment] 2023-07-17 19:53
Yeah, I'm going to guess that this was the issue. Did the other two videos have an issue or did they download successfully?

- `2AV9d8-VIrI`
- `HH5x6kfVy2Y`

**Comment by kriss6557** [comment] 2023-07-17 20:07
they had issues as well. I deleted the download queue/rescan, then I was able to download them.

**Comment by lamusmaser** [comment] 2023-07-17 20:13
That definitely is the issue, then. I wonder if those videos picked up a different format and were able to download, but this one didn't.

Either way, I can see the enhancement in terms of handling this better. @bbilly1 can you review and see if this is something you would like to incorporate or if you believe this is responding as intended. Also, since I know you were working on several enhancements to different areas, can you confirm if this would be fixed by ways of handling in the next version or if we you'd like help incorporating a fix or catch for this.

**Comment by kriss6557** [comment] 2023-07-17 20:49
@lamusmaser thank you for your prompt support.

**Comment by bbilly1** [comment] 2023-07-19 03:49
A container restart would have cleaned the cache too here.

This is there, so a partial download could continue from where it left off, but that doesn't look like it's working. In any case, as we now have proper fail signal with the new task backend, we can handle that more gracefully.

**Comment by bbilly1** [comment] 2023-08-05 05:30
That's now improved in v0.4.0, thanks for reporting.

**Closed by bbilly1** 2023-08-05 05:30 UTC
Labels: bug, pending-release
