### ISSUE TITLE
[Bug]: TubeArchivist isn't responsive on chrome based browser mobile screens (regression)

### ISSUE THREAD

**Issue by adan89lion** [tubearchivist/tubearchivist#616] opened 2023-11-25 11:13 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology DSM 6.2 (64521)

## Describe the bug
When accessing TubeArchivist from mobile devices, the website isn't responsive to small displays. This bug appears after 0.4.3 release, and still persists on 0.4.4 (latest) release. My test device is Samsung Galaxy S23 Ultra (on Android 14) and Google Chrome 119.0.6045.163.

## Steps To Reproduce
1. Upgrade to post TubeArchivist 0.4.3 release (where is bug happens).
2. Browse the TubeArchivist instance from any mobile device.
3. Notice the cropped-out webpage format, users are required to zoom-out to access some features.

## Expected behavior
1. The webpage should be responsive and adjusted for mobile experience.

### Relevant log output

```shell
N/A
```

### Anything else?

This is a screenshot of TubeArchivist installed as a PWA, indicating the cropped-out page.
![Screenshot_20231125](https://github.com/tubearchivist/tubearchivist/assets/6585644/34f42dbe-fcb9-4dbc-9a1f-8cd8e372a65b)

**Comment by trafficman** [comment] 2023-11-28 05:07
I can reproduce this cropping behavior in Chrome on desktop (it begins at the extreme edge of tablet mode), but Firefox behaves as expected (Firefox on top, Chrome on bottom, the mobile versions of both also behave identically):

![image](https://github.com/tubearchivist/tubearchivist/assets/1946372/1787df06-2d90-4845-9f08-bff80d67eccc)

For whatever reason, Chrome seems to be behaving as if "width: 100%;" is absent from the top-banner style sheet, removing it in Firefox creates the same behavior:

![image](https://github.com/tubearchivist/tubearchivist/assets/1946372/966f7e88-0ec1-4207-ac26-e4d3e363f52a)

A current temporary workaround could be to use Firefox mobile when accessing TA from a phone

**Comment by bbilly1** [comment] 2023-12-01 02:44
That must have been introduced in #583. @extome9000 can you look into this?

Or anybody using mobile chrome...

But yes, scaling on mobile firefox is working fine.

**Comment by extome9000** [comment] 2023-12-02 01:34
I did some testing and can confirm that it seems to be affecting Chromium browsers. I tested Brave, Chrome, Edge, and Vivaldi and they all have the same problem. trafficman's explanation is correct. 
I used the `content: url(...)` attribute because it was very convenient for setting a specific banner per theme. I'll try and see if I can find a fix or workaround.

**Comment by bbilly1** [comment] 2023-12-21 04:15
Thanks for reporting, fixed merged in v0.4.5, please update.

**Closed by bbilly1** 2023-12-21 04:15 UTC
Labels: bug, pending-release
