### ISSUE TITLE
[Bug]: Task failed: join() argument must be str, bytes, or os.PathLike object, not 'bool'

### ISSUE THREAD

**Issue by Gaffers2277** [tubearchivist/tubearchivist#519] opened 2023-08-20 13:31 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux - Ubuntu 22.04LTS - Docker

## Describe the bug
I had an issue with Tube Archivst not connecting to Redis so i pulled down the Docker container and recreated it keeping the config folder from the previous container but lost all channels, playlists and videos. So i went to manually import them but i get this error message when i go to import a video downloaded using my previous conatiner instance of Tube Archivist "Task failed: join() argument must be str, bytes, or os.PathLike object, not 'bool'". 

I would expect if the video was downloaded using Tube Achivist it would import correctly. Reading the Manual Import Docs i says to use the info.json file for metadata but I don't have any as i don't think Tube Archivist downloads the info.json files. 

Now i have around 1.68TB of videos, thumbnails and .nfo files (created by Jellyfin) imported into Jellyfin using the script but don't have any of them imported into Tube Archivist. Any way to solve this?

### Relevant log output

```shell
2023-08-20T13:29:33.231484384Z [2023-08-20 14:29:33,230: INFO/MainProcess] Task manual_import[9a9d9180-3bfc-4149-8572-f78bc480d00f] received

2023-08-20T13:29:33.233315790Z [2023-08-20 14:29:33,231: WARNING/ForkPoolWorker-2] manual_import create callback

2023-08-20T13:29:33.241749439Z [2023-08-20 14:29:33,241: WARNING/ForkPoolWorker-2] manual import: {'media': '/cache/import/V-y1vwde8hU.mp4', 'video_id': False, 'metadata': False, 'thumb': False, 'subtitle': []}

2023-08-20T13:29:33.243828027Z [2023-08-20 14:29:33,243: WARNING/ForkPoolWorker-2] id extraction failed from filename: /cache/import/V-y1vwde8hU.mp4

2023-08-20T13:29:33.246325549Z [2023-08-20 14:29:33,246: WARNING/ForkPoolWorker-2] 9a9d9180-3bfc-4149-8572-f78bc480d00f Failed callback

2023-08-20T13:29:33.249644752Z [2023-08-20 14:29:33,248: ERROR/ForkPoolWorker-2] Task manual_import[9a9d9180-3bfc-4149-8572-f78bc480d00f] raised unexpected: TypeError("join() argument must be str, bytes, or os.PathLike object, not 'bool'")

2023-08-20T13:29:33.249679111Z Traceback (most recent call last):

2023-08-20T13:29:33.249684717Z   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task

2023-08-20T13:29:33.249689503Z     R = retval = fun(*args, **kwargs)

2023-08-20T13:29:33.249709658Z                  ^^^^^^^^^^^^^^^^^^^^

2023-08-20T13:29:33.249714489Z   File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__

2023-08-20T13:29:33.249718959Z     return self.run(*args, **kwargs)

2023-08-20T13:29:33.249722912Z            ^^^^^^^^^^^^^^^^^^^^^^^^^

2023-08-20T13:29:33.249726929Z   File "/app/home/tasks.py", line 271, in run_manual_import

2023-08-20T13:29:33.249731181Z     ImportFolderScanner(task=self).scan()

2023-08-20T13:29:33.249735351Z   File "/app/home/src/index/manual.py", line 55, in scan

2023-08-20T13:29:33.249739589Z     self.process_videos()

2023-08-20T13:29:33.249743656Z   File "/app/home/src/index/manual.py", line 139, in process_videos

2023-08-20T13:29:33.249747830Z     self._detect_youtube_id(current_video)

2023-08-20T13:29:33.249751938Z   File "/app/home/src/index/manual.py", line 171, in _detect_youtube_id

2023-08-20T13:29:33.249756108Z     youtube_id = self._extract_id_from_json(current_video["metadata"])

2023-08-20T13:29:33.249760317Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-08-20T13:29:33.249764454Z   File "/app/home/src/index/manual.py", line 196, in _extract_id_from_json

2023-08-20T13:29:33.249768681Z     json_path = os.path.join(self.CACHE_DIR, "import", json_file)

2023-08-20T13:29:33.249773075Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-08-20T13:29:33.249777296Z   File "<frozen posixpath>", line 90, in join

2023-08-20T13:29:33.249781766Z   File "<frozen genericpath>", line 152, in _check_arg_types

2023-08-20T13:29:33.249786083Z TypeError: join() argument must be str, bytes, or os.PathLike object, not 'bool'
```

**Comment by bbilly1** [comment] 2023-08-20 14:51
unclear what happened here, but you'll want to restore the volumes from elastic search to get all back. failing that you have the snapshot, or the json backup files.

manual import is a different thing, for manually importing files downloaded outside of this project. you also have the filesystem rescan to at least partially rebuild a TA archive.

all that is documented in details in the docs.

**Comment by Gaffers2277** [comment] 2023-08-20 15:01
okay, but i don't seem to have any json info files, is there a way to get Tube Archivist to download them with the videos? or is this a different json file? Also where are the db and snapshot files located as i like to have them bound to my drive rather then in docker volumes?

**Comment by bbilly1** [comment] 2023-08-21 13:38
the info json files from yt-dlp get parsed and relevant data gets stored in ES. 

Yes, snapshots are in the docker volume of ES, in the conveniently names *snapshot* folder. Then the JSON backup files are stored in a zip file in /cache/backup, as documented [here](https://docs.tubearchivist.com/settings/#zip-file-index-backup_1). 

You can easily extract the data from a volume, that info is readily available out there.

Ultimately, don't delete stuff that you don't want to delete, and if you do, make sure you have backups. I'm closing this issue, as this is not a bug of tube archivist. Sometimes people on Discord are generous with their time with one on one help like that.

**Closed by bbilly1** 2023-08-21 13:38 UTC
Labels: invalid

**Comment by Jefferderp** [comment] 2023-12-22 21:23
To clarify for future readers, because I was confused at first, this error will occur if your files being imported are not following the [proper naming convention](https://docs.tubearchivist.com/settings/actions/#manual-media-files-import).
