### ISSUE TITLE
[Bug]: Documents being deactivated when cookie not available and required for access

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#597] opened 2023-11-14 02:33 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Unraid

## Describe the bug
While looking into #596, initially the video was deactivated because apparently my cookie had expired (even though TA still claimed it was valid `¯\_(ツ)_/¯` also ref https://github.com/tubearchivist/browser-extension/issues/22)

## Steps To Reproduce
Re-indexed members-only video with a bad (or no) cookie and video was instantly deactivated

## Expected behavior
I would suspect the best course of action would be to look for the standard YT errors:
`Join this channel to get access to members-only content like this video, and other exclusive perks.`
`...something, something private video....`
and if those exist, do not discount the video as deactivated and no longer available

### Relevant log output

```shell
[2023-11-13 20:22:20,099: WARNING/ForkPoolWorker-16] [task][check_reindex] reindex {'video': ['Yg1fdaGgtDE']}
[2023-11-13 20:22:20,221: WARNING/ForkPoolWorker-16] validating cookie
[2023-11-13 20:22:20,289: WARNING/ForkPoolWorker-16] Yg1fdaGgtDE: get metadata from es
[2023-11-13 20:22:20,291: WARNING/ForkPoolWorker-16] Yg1fdaGgtDE: get metadata from youtube
[2023-11-13 20:22:21,714: WARNING/ForkPoolWorker-16] ERROR: [youtube] Yg1fdaGgtDE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[2023-11-13 20:22:21,714: WARNING/ForkPoolWorker-16] https://www.youtube.com/watch?v=Yg1fdaGgtDE: failed to get info from youtube with message ERROR: [youtube] Yg1fdaGgtDE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[2023-11-13 20:22:21,714: WARNING/ForkPoolWorker-16] Yg1fdaGgtDE: deactivate document
[2023-11-13 20:22:24,947: WARNING/ForkPoolWorker-16] c81a36c4-5a24-4252-95cd-24052458b7c7 success callback
```

**Comment by bbilly1** [comment] 2023-11-17 02:30
Honestly, that is working as extended. Cookie functionality probably needs to be fixed in the extension first.

Trying to catch these return messages will likely not be reliable, as that's just text, and will probably change over time. 

If something gets deactivated that shouldn't have, you can refresh the metadata on a per video basis, or you have the command how to do that in the docs too.

**Closed by bbilly1** 2023-11-17 02:30 UTC
Labels: not an issue

**Comment by EpicLPer** [comment] 2023-11-29 04:53
I'm a bit confused as to why this is "working as intended" without wanting to sound harsh or anything ^^"

The cookie gets sent to TA just fine, for my case when manually adding WL and LL to Downloads it (more often than not) works and downloads those playlists just fine, however the Playlists in TA themselves still say "Deactivated". My understanding is that TA should at this point realize that the cookie is active again and automatically mark those playlists "Active", without needing a full Reindex. For me a Reindex run often takes a day if not more by now, which has a high chance of the cookie becoming invalid meanwhile before it finishes.

Really love TA so far, it's exactly what I've been searching for so many years to archive my liked/faved content.

**Comment by EpicLPer** [comment] 2023-12-01 08:04
> What is _working as intended_ is if something is not available on YT anymore, TA will deactivate it. So if your cookie is not valid anymore, this makes your private playlists unavailable, so they will get deactivated.

That of course makes sense, yeah. Tho maybe a good way to handle this is for TA to check what a playlist is set to, so when a rescan happens it tries to reindex "Private" playlists automatically? That would get rid of having to manually reindex a playlist to make it active again :) Or make as an option in settings so you can choose if an automatic rescan should also try to reindex playlists.

> Ultimately, that's not solvable in this project, and you might be better off to use unlisted playlists instead.

This works with normal playlists, but won't work with LL and WL. These can't be set to Unlisted which is the main reason I use TA, to archive videos of those playlists in case they get deleted.


> BTW: You don't need to reindex all videos in a playlist to reactivate it, you can just reindex the playlist itself, that should only take a few seconds. That functionality is mentioned in the docs.

Yeah I think I had some other issues with TA which required a restart of the container to work again, for some reason it barely finished a Reindex after a few days. After the reboot tho it worked in a few seconds.
