### ISSUE TITLE
[Bug][YT-DLP]: Outdated yt-dlp is causing various errors, like getting HTTP Error 403 when downloading videos

### ISSUE THREAD

**Issue by mortalkombatlegend92** [tubearchivist/tubearchivist#522] opened 2023-08-23 07:55 UTC
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Arch Linux

## Describe the bug
Whenever Tube Archivist tries to download a video it comes up with an error 403 forbidden message on the video it tries to download in the downloads tab, I'm guessing its probably because of an outdated yt-dlp
![image](https://github.com/tubearchivist/tubearchivist/assets/127570138/cee7ac34-1704-4b88-b2f3-2796c8fd4851)
## Steps To Reproduce
Add video to queue
Click start download
## Expected behavior
Video downloads without any errors 

### Relevant log output

```shell
{"log":"[2023-08-23 00:50:28,718: INFO/MainProcess] Task download_pending[6ce82e78-0683-4a75-a224-5ff904ad4bd8] received\n","stream":"stderr","time":"2023-08-23T07:50:28.719209386Z"}
{"log":"[2023-08-23 00:50:28,728: WARNING/ForkPoolWorker-2] download_pending create callback\n","stream":"stderr","time":"2023-08-23T07:50:28.72923921Z"}
{"log":"Wed Aug 23 00:50:28 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/download/Ouw_em7EHOw/ (ip 192.168.1.254) !!!\n","stream":"stderr","time":"2023-08-23T07:50:28.734622454Z"}
{"log":"[2023-08-23 00:50:28,973: WARNING/ForkPoolWorker-2] Ouw_em7EHOw: Downloading video\n","stream":"stderr","time":"2023-08-23T07:50:28.973583239Z"}
{"log":"[2023-08-23 00:50:32,019: WARNING/ForkPoolWorker-2] ERROR: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:32.019703225Z"}
{"log":"[2023-08-23 00:50:32,020: WARNING/ForkPoolWorker-2] Ouw_em7EHOw: failed to download with message ERROR: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:32.021738505Z"}
{"log":"[2023-08-23 00:50:32,048: WARNING/ForkPoolWorker-2] Ouw_em7EHOw: Downloading video\n","stream":"stderr","time":"2023-08-23T07:50:32.048441917Z"}
{"log":"[2023-08-23 00:50:34,783: WARNING/ForkPoolWorker-2] ERROR: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:34.783618959Z"}
{"log":"[2023-08-23 00:50:34,783: WARNING/ForkPoolWorker-2] Ouw_em7EHOw: failed to download with message ERROR: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:34.785580593Z"}
{"log":"[2023-08-23 00:50:36,050: WARNING/ForkPoolWorker-2] PLltqRFUQ51yEh3q76CaalpU3fjjrTP2kN: get metadata from es\n","stream":"stderr","time":"2023-08-23T07:50:36.051169226Z"}
{"log":"[2023-08-23 00:50:36,060: WARNING/ForkPoolWorker-2] PLltqRFUQ51yEh3q76CaalpU3fjjrTP2kN: get metadata from youtube\n","stream":"stderr","time":"2023-08-23T07:50:36.060531527Z"}
{"log":"[2023-08-23 00:50:36,685: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden\n","stream":"stderr","time":"2023-08-23T07:50:36.685534587Z"}
{"log":"[2023-08-23 00:50:38,195: WARNING/ForkPoolWorker-2] 6ce82e78-0683-4a75-a224-5ff904ad4bd8 success callback\n","stream":"stderr","time":"2023-08-23T07:50:38.195494814Z"}
{"log":"[2023-08-23 00:50:38,199: INFO/ForkPoolWorker-2] Task download_pending[6ce82e78-0683-4a75-a224-5ff904ad4bd8] succeeded in 9.469081160990754s: None\n","stream":"stderr","time":"2023-08-23T07:50:38.19978Z"}
{"log":"[2023-08-23 00:50:38,199: WARNING/ForkPoolWorker-2] 6ce82e78-0683-4a75-a224-5ff904ad4bd8 return callback\n","stream":"stderr","time":"2023-08-23T07:50:38.200178707Z"}
```

**Comment by bbilly1** [comment] 2023-08-23 10:33
Nice, looks like surfacing these errors introduced in v0.4.0 is working great. :-)

In any case, you are correct, these are yt-dlp errors and not TA errors, we have [latest](https://github.com/yt-dlp/yt-dlp/releases/latest) (as of to day) in TA:
```bash
~ ❯ docker exec -it tubearchivist yt-dlp --version
2023.07.06
```

Fix is incoming: https://github.com/yt-dlp/yt-dlp/issues/7811. But ultimately, as you have seen in the know limitations, we depend on yt-dlp as upstream. 

I saw some of them too, but in my case, this it's still downloading with the retry logic, yours too?

**Comment by mortalkombatlegend92** [comment] 2023-08-23 10:39
Oh my bad, i didn't even notice the latest one was the broken one, which confused me even more when it worked locally for me. Yeah I'll wait for the yt-dlp update, thanks

**Comment by lamusmaser** [comment] 2023-08-23 19:46
Could this be utilized for an enhancement, where we prefix those calls with `YT-DLP` or something similar?

**Comment by bbilly1** [comment] 2023-08-24 03:48
> Could this be utilized for an enhancement, where we prefix those calls with `YT-DLP` or something similar?

Sorry, I don't think I'm following. Can you elaborate?

**Comment by lamusmaser** [comment] 2023-08-24 20:02
I wasn't clear in my statement, either.

In the logs, could we prefix yt-dlp error responses with `YT-DLP`, to indicate that they are from yt-dlp? For example, this line:
```
{"log":"[2023-08-23 00:50:34,783: WARNING/ForkPoolWorker-2] ERROR: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:34.783618959Z"}
```

would then turn into this line, for instance:
```
{"log":"[2023-08-23 00:50:34,783: WARNING/ForkPoolWorker-2] ERROR [YT-DLP]: unable to download video data: HTTP Error 403: Forbidden\n","stream":"stderr","time":"2023-08-23T07:50:34.783618959Z"}
```
Or however we want to format it.

**Comment by nebakanezzer** [comment] 2023-09-02 07:21
seeing the same, also proxy is giving the same 403 error where directly accessing ip:8000 works. nothing changed whatsoever.

**Comment by fake-name** [comment] 2023-09-02 20:41
So I'm understanding this is fixed in newer YT-DLP. So how do we update YT-DLP?

Entering into the container, YT-DLP is not installed through pip, so it's normal selfupdate mechanism doesn't see any updates (admittedly, there hasn't been a new formal release). Installing a newer version manually causes a huge pile of errors when tubearchivist tries to start.

**Comment by mortalkombatlegend92** [comment] 2023-09-09 02:20
Yeah having yt-dlp installed through pip would be nice, then we can easily update it on our own without the need to wait for a tubearchivist update

**Comment by lamusmaser** [comment] 2023-09-09 03:17
What makes you assume you can't update via pip? That is the recommended method for updating `yt-dlp` in case of any issues, and we haven't heard any issues from those we've recommended this to. The only other action is to restart the container so python pulls in the updated version. 

It does come with a caveat: if `yt-dlp` changes or removes functionality and it breakscapability with TA, you'll probably have to rebuild the container to pull the earlier, working `yt-dlp` version.

**Comment by mortalkombatlegend92** [comment] 2023-09-09 03:30
I did some more testing and it looks like the latest version of yt-dlp even if you download it manually and run it in the tubearchivist docker container it displays a 403 error
![image](https://github.com/tubearchivist/tubearchivist/assets/127570138/fcbf53c8-1f06-47f8-9484-63192c66126c)
While running outside of the docker container proves to be successful
 
![image](https://github.com/tubearchivist/tubearchivist/assets/127570138/7b5ccd69-a36d-4c2d-a500-49c1802beba3)

**Comment by fake-name** [comment] 2023-09-09 03:46
> What makes you assume you can't update via pip? That is the recommended method for updating yt-dlp in case of any issues, and we haven't heard any issues from those we've recommended this to. The only other action is to restart the container so python pulls in the updated version.

You can't update it via pip because `yt-dlp` has not released a version that fixes the 403 error issues to PyPI. 

The version installed by pip cannot be updated to a non-pip upstream.

**Comment by fake-name** [comment] 2023-09-09 04:07
Further notes: This seems to be something in the container stuff tripping some sort of detection. 

If I install yt-dlp from git in a generic debian 12 VM, it works.  If I do *exactly* the same thing inside the tubearchivist container, it fails. 

In both cases, this is with https://github.com/yt-dlp/yt-dlp/commit/5d0395498d7065aa5e55bac85fa9354b4b0d48eb as the installed yt-dlp version.

**Comment by lamusmaser** [comment] 2023-09-11 13:47
The pip reference is required for Python to see it. It fails to start because Python cannot see the package.

**Comment by fake-name** [comment] 2023-09-12 06:01
What? No, pip sees the package fine. The issue is **the version of `yt-dlp` on PyPi is broken**. There has not been a new version of `yt-dlp` since July. 

Basically, `yt-dlp` installed via pip/pypi cannot update itself. The distributed binary can update to things like a nightly build. 

The second issue is completely unrelated to tubearchivist. Basically, I uninstalled yt-dlp from PyPi, cloned the yt-dlp repo, and installed the current master. Inside the container, yt-dlp fails. The exact same commit of yt-dlp installed outside docker (in a plain-old debian 12 VM) works fine.

**Comment by fake-name** [comment] 2023-09-13 07:04
> Python interlocking API

That's not a thing. I think you have a word wrong there.

----

In any event, I think I understand what you're trying to say. That's why I cloned the repo and installed it from source. 

Anyways, the underlying issue is that tubearchivist as-is-available in docker **is broken and cannot download from youtube currently**. Discussions of you misunderstanding how I was experimenting with trying to update things aren't relevant.

**Comment by bbilly1** [comment] 2023-09-25 05:18
Until we can create a new release, I've added some instructions how to update yt-dlp inside the container for the impatient:
https://docs.tubearchivist.com/advanced/#manual-yt-dlp-update

As the warning states, only do this if you are willing and able to debug things on your own and share your fixes.

**Comment by K1Hyve** [comment] 2023-09-30 21:35
What is blocking a release right now?
Manually updating the container doesn't seem to work for me since I still get same error message and after a restart the version reverts back to the image version. I'm running this on Kubernetes.
Since this project depends on the upstream project is it possible to have a decouple tubearchivist releases from yt-dlp release? Would be good if it was an environment variable or an option in the settings menu.
I'm use TA solely to download videos from my private playlist and since it's functionality isn't working I can't do anything at all.

**Comment by lamusmaser** [comment] 2023-09-30 21:57
Since we are wholly dependent on `yt-dlp` for downloading, we cannot fully decouple the two. There is a new unstable version that was published that does incorporate a newer version of `yt-dlp`, and when the newest release comes out it should have the latest stable version of `yt-dlp`, as well.

**Comment by K1Hyve** [comment] 2023-09-30 22:05
From decoupling I meant `yt-dlp` version not being tied to the docker image of TA and having an option to select the `yt-dlp` version inside the TA in one way or another and it would download that related from Github. It will also make easy for @ bbilly1 to maintain this project since they won't need to make releases often and deal less with people that come here saying stuff isn't working.

**Comment by bbilly1** [comment] 2023-10-07 10:01
newest TA v0.4.2 ships yt-dlp 2023.10.7, fixing issues collected here.

**Closed by bbilly1** 2023-10-07 10:01 UTC
Labels: invalid, pending-release

**Comment by Dontkickmi22** [comment] 2023-11-29 17:28
Getting the below two errors, wondering if anyone else been seeing these?

- unable to download video data: HTTP Error 403: Forbidden
- Requested format is not available. Use --list-formats for a list of available formats

I am on rpi4 TA 0.4.4 ES 8.11.0. 
One host has yet to hit above errors, where a couple other hosts had to stop.

**Comment by PhuriousGeorge** [comment] 2023-11-30 02:13
> Getting the below two errors, wondering if anyone else been seeing these?
> 
> * unable to download video data: HTTP Error 403: Forbidden
> * Requested format is not available. Use --list-formats for a list of available formats

#1 Can also be YT rate-limiting or soft-banning you if you've grabbed a lot of stuff or queried a lot of metadata.  YT is getting very aggressive at this lately - try behind a VPN if you can

#2 Is tied to whatever your format preference is set in TA settings as not being available on the YT (ie: you only want 4k and the video is only published in 320p or you want opus codec audio and they only have...well whatever the options are)

**Comment by Dontkickmi22** [comment] 2023-11-30 03:14
> > Getting the below two errors, wondering if anyone else been seeing these?
> > 
> > * unable to download video data: HTTP Error 403: Forbidden
> > * Requested format is not available. Use --list-formats for a list of available formats
> 
> 1 - Can also be YT rate-limiting or soft-banning you if you've grabbed a lot of stuff or queried a lot of metadata. YT is getting very aggressive at this lately - try behind a VPN if you can
> 
> 2 - Is tied to whatever your format preference is set in TA settings as not being available on the YT (ie: you only want 4k and the video is only published in 320p or you want opus codec audio and they only have...well whatever the options are)

Thank you x 3. 

1 - That ring the bell. The others were on while that one host I mentioned happens been off, and just brought back up. 
2 - For other's reference, my format preference is set at default, which is best quality it could get.
